server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/know?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  #配置redis
  redis:
    host: localhost
    port: 6379
    #用索引为1的数据库
    database: 1
    jedis:
      pool:
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池最大连接数（使用负数表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负数表示没有限制）
        max-wait: 60000
    password:
    #连接超时时间（毫秒）
    timeout: 5000
  #邮箱配置
  mail:
    #邮件服务器
    host: smtp.qq.com
    #用户名
    username: 1540215426@qq.com
    #16位校验码，邮箱自动生成
    password: cfoqeqxqisxrgjif
    #端口
    properties.mail.smtp.port: 25
    #发件邮箱，和用户名一致
    from: 1540215426@qq.com
    default-encoding: utf-8
#mybatis配置
mybatis:
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
  #实体类所在包名
  type-aliases-package: com.zhifou.model
#通用mapper配置
mapper:
  #共用接口类路径
  mappers: cn.archforce.zhifou.mappers.BaseMapper
  identity: MYSQL
#分页pageHelper
pagehelper:
  #配置数据库
  helper-dialect: mysql
  #配置分页参数合理化，页数小于1查询第一页，页数大于最大值查询最后一页
  reasonable: true
  #支持通过Mapper接口参数来传递分页参数
  support-methods-arguments: true